#!/usr/bin/env bash
set -euo pipefail

HTTP_COMMAND=${HTTP_COMMAND:-http}

THEME_URLS=(
    https://raw.githubusercontent.com/catppuccin/warp/refs/heads/main/themes/catppuccin_latte.yml
    https://raw.githubusercontent.com/catppuccin/warp/refs/heads/main/themes/catppuccin_frappe.yml
    https://raw.githubusercontent.com/catppuccin/warp/refs/heads/main/themes/catppuccin_macchiato.yml
    https://raw.githubusercontent.com/catppuccin/warp/refs/heads/main/themes/catppuccin_mocha.yml
)

download_warp_theme() {
    local url=$1
    local filename
    filename="$(basename "${url}")"
    local filepath="./${filename}"

    echo "Fetching ${filename} from ${url}"
    # shellcheck disable=SC2086
    ${HTTP_COMMAND} "${url}" >"${filepath}"
}

install_themes() {
    warp_themes_dir="$HOME/.warp/themes/"
    mkdir -p "${warp_themes_dir}"
    cd "${warp_themes_dir}"
    echo Saving to "${warp_themes_dir}"

    for theme_url in "${THEME_URLS[@]}"; do
        download_warp_theme "${theme_url}"
    done
}

install_themes
